# Conteneur Nginx pour le front
FROM nginx:alpine

# Copie frontend existant dans Nginx
COPY ./frontend/public /usr/share/nginx/html

# Exposer le port 80
EXPOSE 80

# Lance Nginx
CMD ["nginx", "-g", "daemon off;"]